#!/usr/bin/env python3
"""Regenerate ``backend/app/analysis/wordmark_data.py`` from the product
wordmark asset ``frontend/src/assets/mobark-wordmark.svg`` (the same file the
frontend TopBar renders) so the branded PDF cover can draw the REAL wordmark
in-container (the image only ships ``backend/`` + ``frontend/dist``).

Run from the repo root:
    python3 scripts/sync_wordmark.py

The generated module is the M1 vendored-data precedent (scripts/sync_mastg.py
→ vendored MASTG mapping): the SVG is parsed ONCE here into a compact,
render-ready form. Only the vector ``d`` paths (the wordmark uses the
M/L/H/V/Z subset) + the white raster brand text survive; gradients are
flattened to their midpoint hex at generation time; the raster is CROPPED
to the exact region the SVG's pattern matrix exposes (so the report draws
the same glyphs the browser shows) and stored as a small RGBA PNG. Drop
shadows (SVG filters) are deliberately skipped - the PDF band is flat.
"""
from __future__ import annotations

import base64
import hashlib
import io
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SVG_PATH = ROOT / "frontend" / "src" / "assets" / "mobark-wordmark.svg"
OUT_PATH = ROOT / "backend" / "app" / "analysis" / "wordmark_data.py"


def _midpoint(hexes: list[str]) -> str:
    """Flatten a gradient to the midpoint of its stops."""
    r = sum(int(h[1:3], 16) for h in hexes) // len(hexes)
    g = sum(int(h[3:5], 16) for h in hexes) // len(hexes)
    b = sum(int(h[5:7], 16) for h in hexes) // len(hexes)
    return f"#{r:02x}{g:02x}{b:02x}"


def main() -> int:
    svg = SVG_PATH.read_text(encoding="utf-8")

    vb = re.search(r'viewBox="(\d+) (\d+) (\d+) (\d+)"', svg)
    assert vb, "no viewBox"
    vw, vh = int(vb.group(3)), int(vb.group(4))

    # --- gradients -> midpoint hex -----------------------------------------
    grads: dict[str, str] = {}
    for g in re.finditer(
        r'<linearGradient id="([^"]+)"[^>]*>(.*?)</linearGradient>', svg, re.S
    ):
        stops = re.findall(r'stop-color="(#[0-9a-fA-F]{6})"', g.group(2))
        if stops:
            grads[g.group(1)] = _midpoint(stops)

    # --- vector paths (deduped: paint0/paint1 and the FEFFFC duplicate) ----
    paths: list[tuple[str, str]] = []
    for p in re.finditer(r'<path d="([^"]+)" fill="([^"]+)"', svg):
        d, fill = p.group(1), p.group(2)
        if fill.startswith("url(#"):
            fill = grads[fill[5:-1]]
        if (d, fill) not in paths:
            paths.append((d, fill))

    # --- raster: the rect the pattern fills + the visible crop -------------
    rect = re.search(
        r'<rect x="([\d.]+)" y="([\d.]+)" width="([\d.]+)" '
        r'height="([\d.]+)" fill="url\(#pattern0[^"]*"',
        svg,
    )
    assert rect, "no pattern rect"
    rx, ry, rw, rh = (float(v) for v in rect.groups())

    mat = re.search(
        r'<use xlink:href="#image0[^"]*" transform="matrix\('
        r"(-?[\d.]+) (-?[\d.]+) (-?[\d.]+) (-?[\d.]+) (-?[\d.]+) (-?[\d.]+)\)\"",
        svg,
    )
    assert mat, "no pattern matrix"
    a, _b, _c, d, e, f = (float(v) for v in mat.groups())

    img = re.search(
        r'<image id="image0[^"]*" width="(\d+)" height="(\d+)"[^>]*?'
        r'xlink:href="data:image/png;base64,([^"]+)"',
        svg,
    )
    assert img, "no embedded raster"
    iw, ih = int(img.group(1)), int(img.group(2))
    raw = base64.b64decode(img.group(3))
    im = Image.open(io.BytesIO(raw)).convert("RGBA")

    # Image coords where the pattern box maps to [0,1]x[0,1]:
    #   x' = a*x + e, y' = d*y + f  ->  x = (x'-e)/a, y = (y'-f)/d
    ix0, ix1 = (0 - e) / a, (1 - e) / a
    iy0, iy1 = (0 - f) / d, (1 - f) / d
    box = (
        max(0, int(ix0)),
        max(0, int(iy0)),
        min(iw, int(ix1)),
        min(ih, int(iy1)),
    )
    assert box[2] > box[0] and box[3] > box[1], f"empty raster crop {box}"
    crop = im.crop(box)
    # The raster is drawn at ~114 pt wide on the cover, so the 1128 px crop
    # is ~10x oversampled - downscale 4x (LANCZOS keeps the anti-aliased
    # edges) before normalizing to pure white glyphs, so the module stays
    # small (~10 KB vs 460 KB). The report composites white text onto the
    # emerald band either way.
    small = crop.resize((crop.width // 4, crop.height // 4), Image.LANCZOS)
    white = Image.new("RGBA", small.size, (255, 255, 255, 0))
    white.putalpha(small.getchannel("A"))
    buf = io.BytesIO()
    white.save(buf, "PNG", optimize=True)
    png_b64 = base64.b64encode(buf.getvalue()).decode("ascii")

    # --- emit the module ----------------------------------------------------
    svg_sha = hashlib.sha256(svg.encode("utf-8")).hexdigest()
    lines = [
        '"""MobARK wordmark - GENERATED by scripts/sync_wordmark.py from',
        "frontend/src/assets/mobark-wordmark.svg (do not edit by hand; re-run",
        "the sync script after touching the SVG - a test compares this file's",
        "SVG_SHA256 against the live asset to catch stale vendored data). The",
        "report PDF cover draws the real brand wordmark: vector logo paths +",
        "the white raster brand text (cropped to the SVG's pattern-visible",
        "region), flipped to PDF y-up and scaled by the renderer.",
        '"""',
        "",
        f'# SHA-256 of the source SVG this module was generated from.',
        f'SVG_SHA256 = "{svg_sha}"',
        "",
        f"VIEWBOX_W = {vw}",
        f"VIEWBOX_H = {vh}",
        "",
        "# (d, fill_hex) - gradients flattened to their midpoint.",
        "PATHS = [",
    ]
    for d, fill in paths:
        lines.append(f"    ({d!r}, {fill!r}),")
    lines += [
        "    ]",
        "",
        "# The white raster brand text: its rect in viewBox coords + a small",
        "# RGBA PNG (white glyphs on transparency - mask='auto' composites it",
        "# onto the emerald band).",
        "RASTER = {",
        f'    "x": {rx}, "y": {ry}, "w": {rw}, "h": {rh},',
        f'    "png_b64": {png_b64!r},  # noqa: E501 (generated raster)',
        "    }",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {OUT_PATH}")
    crop_w, crop_h = box[2] - box[0], box[3] - box[1]
    print(f"  viewBox {vw}x{vh} · {len(paths)} paths · raster crop {crop_w}x"
          f"{crop_h} of {iw}x{ih} -> {len(png_b64)} b64 chars")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
